In [13]:
import pandas as pd

In [15]:
df=pd.read_csv('loan.csv')
df

age  gender    occupation education_level marital_status  income  \
0    32    Male      Engineer      Bachelor's        Married   85000   
1    45  Female       Teacher        Master's         Single   62000   
2    28    Male       Student     High School         Single   25000   
3    51  Female       Manager      Bachelor's        Married  105000   
4    36    Male    Accountant      Bachelor's        Married   75000   
..  ...     ...           ...             ...            ...     ...   
56   39    Male     Architect        Master's        Married  100000   
57   25  Female  Receptionist     High School         Single   32000   
58   43    Male        Banker      Bachelor's        Married   95000   
59   30  Female        Writer        Master's         Single   55000   
60   38    Male          Chef     Associate's        Married   65000   

    credit_score loan_status  
0            720    Approved  
1            680    Approved  
2            590      Denied  
3            780    Approved  
4            710    Approved  
..           ...         ...  
56           770    Approved  
57           570      Denied  
58           760    Approved  
59           650    Approved  
60           700    Approved  

[61 rows x 8 columns]

In [17]:
df.isna().sum()

age                0
gender             0
occupation         0
education_level    0
marital_status     0
income             0
credit_score       0
loan_status        0
dtype: int64

In [19]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,classification_report,confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [21]:
le=LabelEncoder()
for column in ['gender','occupation','education_level','marital_status','income','loan_status']:
    df[column]=le.fit_transform(df[column])
df

age  gender  occupation  education_level  marital_status  income  \
0    32       1          12                1               0      24   
1    45       0          35                4               1      15   
2    28       1          33                3               1       0   
3    51       0          16                1               0      31   
4    36       1           0                1               0      20   
..  ...     ...         ...              ...             ...     ...   
56   39       1           2                4               0      30   
57   25       0          27                3               1       3   
58   43       1           4                1               0      28   
59   30       0          37                4               1      12   
60   38       1           5                0               0      16   

    credit_score  loan_status  
0            720            0  
1            680            0  
2            590            1  
3            780            0  
4            710            0  
..           ...          ...  
56           770            0  
57           570            1  
58           760            0  
59           650            0  
60           700            0  

[61 rows x 8 columns]

In [23]:
x=df[['age','gender','occupation','education_level','marital_status','income','credit_score']]
x

age  gender  occupation  education_level  marital_status  income  \
0    32       1          12                1               0      24   
1    45       0          35                4               1      15   
2    28       1          33                3               1       0   
3    51       0          16                1               0      31   
4    36       1           0                1               0      20   
..  ...     ...         ...              ...             ...     ...   
56   39       1           2                4               0      30   
57   25       0          27                3               1       3   
58   43       1           4                1               0      28   
59   30       0          37                4               1      12   
60   38       1           5                0               0      16   

    credit_score  
0            720  
1            680  
2            590  
3            780  
4            710  
..           ...  
56           770  
57           570  
58           760  
59           650  
60           700  

[61 rows x 7 columns]

In [25]:
y=df[['loan_status']]
y

loan_status
0             0
1             0
2             1
3             0
4             0
..          ...
56            0
57            1
58            0
59            0
60            0

[61 rows x 1 columns]

In [27]:
ss=StandardScaler()
ss.fit_transform(x)

array([[-0.60822442,  0.98373875, -0.43329842, -0.75569778, -0.80538727,
         0.35125047,  0.14101548],
       [ 0.94765289, -1.01653005,  1.66296945,  1.43942435,  1.2416387 ,
        -0.48353961, -0.41394865],
       [-1.0869559 ,  0.98373875,  1.48068529,  0.70771697,  1.2416387 ,
        -1.87485641, -1.66261794],
       [ 1.66575011, -1.01653005, -0.06873009, -0.75569778, -0.80538727,
         1.00053165,  0.97346167],
       [-0.12949294,  0.98373875, -1.5270034 , -0.75569778, -0.80538727,
        -0.01976734,  0.00227444],
       [-1.56568738, -1.01653005,  0.20469615, -1.48740516,  1.2416387 ,
        -1.04006633, -0.96891278],
       [ 0.58860428,  0.98373875, -0.15987218, -0.02399041, -0.80538727,
         1.27879501,  1.1122027 ],
       [-0.96727303, -1.01653005, -1.25357715, -0.75569778,  1.2416387 ,
        -1.41108414, -1.24639485],
       [-0.00981007,  0.98373875, -0.25101426,  1.43942435, -0.80538727,
         0.62951383,  0.55723857],
       [ 1.3067015 , -1.0165

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
print(x_train,x_test,y_train,y_test)

    age  gender  occupation  education_level  marital_status  income  \
4    36       1           0                1               0      20   
44   42       1          15                2               0      36   
19   53       0          23                2               0      29   
47   48       0           9                2               0      38   
52   37       1          12                1               0      27   
25   28       0          36                2               1      20   
57   25       0          27                3               1       3   
15   27       0           8                1               1      11   
58   43       1           4                1               0      28   
27   43       0          13                4               0      26   
9    48       0           9                2               0      39   
30   27       1          21                0               1       6   
36   35       1          12                4               0    

In [31]:
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
model

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [33]:
y_pred=model.predict(x_test)
y_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [35]:
acc=accuracy_score(y_test,y_pred)
acc

0.9473684210526315

In [37]:
cc=confusion_matrix(y_test,y_pred)
cc

array([[14,  1],
       [ 0,  4]], dtype=int64)

In [39]:
ccc=classification_report(y_test,y_pred)
ccc

'              precision    recall  f1-score   support\n\n           0       1.00      0.93      0.97        15\n           1       0.80      1.00      0.89         4\n\n    accuracy                           0.95        19\n   macro avg       0.90      0.97      0.93        19\nweighted avg       0.96      0.95      0.95        19\n'

In [41]:
pp=precision_score(y_test,y_pred)
pp

0.8

In [43]:
new_data=np.array([[32,1,12,1,0,24,720]])
new=ss.transform(new_data)
predicted_prob=model.predict(new)
print(predicted_prob[0])

1


C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
